buildImage = 'ghcr.io/railwayapp/nixpacks:latest'

[phases.setup]
nixPkgs = [
    "nodejs_22",
    "pnpm-9_x",
    "openssl",
]

[phases.install]
cmds = ["npm install -g corepack", "corepack enable", "corepack prepare pnpm@9 --activate", "pnpm install"]
